theme = "hugo-dhruv-archives"
baseURL = "/"
languageCode = "en-us"
title = "Dhruv Archives"

[params]
    google_fonts = [
        ["Jersey 15", "400"],
        ["Tomorrow", "400,700"],
        ["Noto Sans", "400, 700"],
        ["Courier Prime", "400, 700"],
        ["Jersey 25 Charted", "400"]
    ]

    # theme color (checkout font-variable.css))
    heading_font = "Jersey 15"
    heading_weight = "400"
    body_font = "Courier Prime"
    body_weight = "400, 700"
    body_h_weight = "700"

    # Shows up in front page
    mainSections = ["blog"]

    # Background colors
    color = "linen"  # background color (search to add more) linen, grey, wheat
    
    github = "dhruv0000"
    linkedin = "dhruv0000"
    twitter = "dhruv_archives"
    behance = "dhruv-archives"

    favicon = "icons/van-gough.ico"                   # customize the default favicon
    appleTouchIcon = "icons/van-gough.png"   # customize the default 
  
    [[params.aboutItems]]
        title = "./whoami"
        description = "Software engineer specializing in distributed systems and cloud architecture. Currently pursuing my MS in Information Networking at Carnegie Mellon University."
  
    [[params.aboutItems]]
        title = "Things I did:"
        description = "My work spans full-stack development, system design, and infrastructure optimization. I build resilient systems that scale efficiently while maintaining clear and intuitive interfaces. Checkout my <a href='/resume/'>resume</a> for more details."
    
    [menu]
        [[menu.main]]
            identifier = "audio-video"
            name = "Audio/Video"
            url = "/audio-video/"
            weight = 10
        [[menu.main]]
            identifier = "resume"
            name = "Resume"
            url = "/resume/"
            weight = 10
        [[menu.main]]
            identifier = "blog"
            name = "Blogs"
            url = "/blog/"
            weight = 10
        [[menu.main]]
            identifier = "contact"
            name = "Contact"
            url = "/contact/"
            weight = 10

[privacy]
  [privacy.x]
    disable = false
    enableDNT = true
