theme = "hugo-dhruv-archives"
baseURL = "/"
languageCode = "en-us"
title = "Dhruv Archives"

[params]
    google_fonts = [
        ["Jersey 15", "400"],
        ["Tomorrow", "400,700"],
        ["Jersey 25 Charted", "400"]
    ]

    heading_font = "Jersey 25 Charted"
    heading_font_weight = "400"
    body_font = "Tomorrow"
    body_font_weight = "400, 700"

    github = "dhruv0000"
    linkedin = "dhruv0000"
    twitter = "realDhruvPatel"
    behance = "dhruv-archives"
    animation = "animation/banner.gif"

    favicon = "icons/van-gough.png"                   # customize the default favicon
    appleTouchIcon = "icons/van-gough.png"   # customize the default 
  
    [[params.aboutItems]]
        title = "Education"
        description = "Carnegie Mellon University, MS in Software Engineering"
  
    [[params.aboutItems]]
        title = "Experience"
        description = "Software Engineer with experience in distributed systems, cloud architecture, and full-stack development"
    
    [[params.aboutItems]]
        title = "Projects"
        description = "Still working on it. Stay tuned!"
    
    [menu]
        [[menu.main]]
            identifier = "music"
            name = "Music"
            url = "/music/"
            weight = 10
        [[menu.main]]
            identifier = "resume"
            name = "Resume"
            url = "/resume/"
            weight = 10
        [[menu.main]]
            identifier = "blog"
            name = "Blogs"
            url = "/blog/"
            weight = 10

[privacy]
  [privacy.x]
    disable = false
    enableDNT = true