theme = "hugo-dhruv-archives"
baseURL = "https://dhruv-archives.com/"
languageCode = "en-us"
title = "Dhruv Archives"

[params]
    google_fonts = [
        ["Jersey 15", "400"],
        ["Tomorrow", "400,700"],
        ["Jersey 25 Charted", "400"]
    ]

    github = "dhruv0000"
    linkedin = "dhruv0000"
    twitter = "realDhruvPatel"
    behance = "dhruv-archives"
    animation = "animation/banner.gif"


    welcomeMessage = "Welcome to my part of world wide web. Lets start with some music?"
  
    [[params.aboutItems]]
        title = "Education"
        description = "Carnegie Mellon University, MS in Software Engineering"
  
    [[params.aboutItems]]
        title = "Experience"
        description = "Software Engineer with experience in distributed systems, cloud architecture, and full-stack development"