theme = "hugo-dhruv-archives"
baseURL = "/"
languageCode = "en-us"
title = "Dhruv Archives"

[params]
    google_fonts = [
        ["Jersey 15", "400"],
        ["Tomorrow", "400,700"],
        ["Noto Sans", "400, 700"],
        ["Jersey 25 Charted", "400"]
    ]

    heading_font = "Jersey 25 Charted"
    heading_font_weight = "400"
    body_font = "Noto Sans"
    body_font_weight = "400, 700"

    github = "dhruv0000"
    linkedin = "dhruv0000"
    twitter = "realDhruvPatel"
    behance = "dhruv-archives"
    animation = "animation/banner.gif"

    favicon = "icons/van-gough.png"                   # customize the default favicon
    appleTouchIcon = "icons/van-gough.png"   # customize the default 
  
    [[params.aboutItems]]
        title = "./whoami"
        description = "Software engineer specializing in distributed systems and cloud architecture. Currently pursuing my MS in Information Networking at Carnegie Mellon University."
  
    [[params.aboutItems]]
        title = "Things I did:"
        description = "My work spans full-stack development, system design, and infrastructure optimization. I build resilient systems that scale efficiently while maintaining clear and intuitive interfaces. Checkout my <a href='/resume/'>resume</a> for more details."
        
    [menu]
        [[menu.main]]
            identifier = "music"
            name = "Music"
            url = "/music/"
            weight = 10
        [[menu.main]]
            identifier = "resume"
            name = "Resume"
            url = "/resume/"
            weight = 10
        [[menu.main]]
            identifier = "blog"
            name = "Blogs"
            url = "/blog/"
            weight = 10

[privacy]
  [privacy.x]
    disable = false
    enableDNT = true