name: Download Resume PDF

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  download-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: personal-452921 # Replace with your project ID

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Download Resume as PDF (Requires API call)
        run: |
          # This is a placeholder.  You need to implement the actual API call here.
          # Use the Google Drive API v3 to get the file ID of your Google Doc.
          # Then, use the Google Docs API or Drive API to export it as a PDF.
          # Example using curl (replace placeholders with your file ID and appropriate export parameters):
          # curl -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
          #      "https://www.googleapis.com/drive/v3/files/{your_file_id}/export?mimeType=application/pdf" \
          #      -o resume.pdf

      - name: Upload PDF (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf
