name: resume-pdf-update.v1

on:
  push:
    branches:
      - main

jobs:
  download-resume:
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Write credentials file
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > credentials.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/credentials.json" >> $GITHUB_ENV
      
      - name: 'Verify account info'
        run: gcloud auth list

      - name: Download Resume as PDF
        run: |
          curl -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
               "https://www.googleapis.com/drive/v3/files/1fJJo3oNB5uM001wyZwGufoIH_EVlie4qRM4k5MXXNL0/export?mimeType=application/pdf" \
               -o resume.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf